version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
    - ./mongo-data/:/data/db
    # command: --wiredTigerCacheSize 1.5

  nest:
    container_name: nest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000 
    volumes:
      - ..:/opt/app/top-api/
    env_file:
      - .env